### ISSUE TITLE
Talents other than normal attack also described as "Normal Attack" on Edit page

### ISSUE THREAD

**Issue by tilda** [glaciyan/gscale#51]
See image below for clarification in case title doesn't make any sense (which I have a hunch it doesn't, lol)

![image](https://user-images.githubusercontent.com/8301262/147830378-4e4dc42d-b4fd-48bb-a904-8d772cbe5fb2.png)

**Comment by glaciyan** [comment]
Fixed! 76e921fe610e66250882ec6763b6fcc576f235d2 Thanks for the report
