### ISSUE TITLE
Suggestions for new features

### ISSUE THREAD

**Issue by merenge5050** [glaciyan/gscale#83]
I am Japanese.
I also use a translation tool to send this message.
I'm sorry if there are some sentences that are not correct.
First of all, I would like to thank you for creating this wonderful site.

[Suggestions for new features].
First. I would like to be able to swap the order of characters in [Your Builds].

Second. I would like the ability to input the materials I have and calculate the amount I am missing!

Third. I would also like to see a screen for training weapons.

I'm not used to using github, so sorry if there are any mistakes.

I'm satisfied with the current version that I use it every day.
Thank you.

**Comment by merenge5050** [comment]
I was impressed by the reflection of the two characters!
You guys are the best!

**Comment by glaciyan** [comment]
Thank you very much! Some of your suggestions are planned already :). Unfortunately I am very busy with my studies.

First. First thing I want to do, when I can work on this project again.
Second. Something I want to extend in the future. It works currently when you upgrade the level when you already have selected something.
Third. Is a rejected feature, sorry.

We currently have some people working on updating the website with new characters. I was able to update this project some weeks ago with some small things.

Again thank you very much for the kind words, it keeps me motivated to work on this project!
